### PR TITLE
Upsampling of minority class done 

### PR DESCRIPTION
**Pull request by sakshamj74**

### CODE REVIEW

**Comment by Nish-19** [comment]
@sakshamj74  I am still not able to view the file. Can someone confirm whether the keras_classification.ipynb file committed here is opening or not?  @atm1504 or @saturn660 is it opening/viewable for you?

**Comment by confifu** [comment]
@Nish-19 keras_classification.ipynb is not loading. I think the file is too large.

**Comment by sakshamj74** [comment]
@Nish-19 any way to overcome this

**Comment by Nish-19** [comment]
@sakshamj74 can you provide a google drive link to the code?

**Comment by sakshamj74** [comment]
@Nish-19 Please have a look.
https://drive.google.com/file/d/16Ijmr5nnf-NIc0fYH_6BWwd-glWGU6Be/view?usp=sharing

**Comment by sakshamj74** [comment]
@Nish-19 I have also uploaded the file again.May be this time it will work.

**Comment by confifu** [comment]
@sakshamj74 You should only display important results in the jupyter notebook. Displaying head and shape you transform the dataframe is not necessary. Also make the cells bigger. Each cell is one line in your notebook. The notebook representation becomes much larger with each added cell. Maybe combine more of those cells together to perform one action.

**Comment by Nish-19** [comment]
@sakshamj74 it is working, yes.

**Pull request merged**
